name: MuseDev

on: pull_request

jobs:
  analyze_src:
    name: Source Branch Analysis
    runs-on: ubuntu-latest
    # container:
    #     image: musedev/analyst
    #     credentials:
    #         username: tommd
    #         password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Produce src artifact
          run: |
              echo "run: analyst -t $GITHUB_WORKSPACE -C $GITHUB_HEAD_REF" > lift-src-results.json
              echo "$(git -C $GITHUB_WORKSPACE rev-parse --head $GITHUB_HEAD_REF)" > lift-commit
        - name: Upload src artifact
          uses: actions/upload-artifact@v2
          with:
            name: lift_src_results
            path: lift*

  analyze_dst:
    name: Destination Branch Analysis
    runs-on: ubuntu-latest
    # container:
    #     image: musedev/analyst
    #     credentials:
    #         username: tommd
    #         password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Produce dst artifact
          run: "echo \"run: analyst -t $GITHUB_WORKSPACE -C $GITHUB_BASE_REF\" > lift-dst-results.json"
        - name: Upload dst artifact
          uses: actions/upload-artifact@v2
          with:
            name: lift_dst_results
            path: lift-dst-results.json

  unify_results:
    name: Distill Result
    needs: [analyze_src, analyze_dst]
    runs-on: ubuntu-latest
    # container:
    #     image: musedev/analyst
    #     credentials:
    #         username: tommd
    #         password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Get Dst
          uses: actions/download-artifact@v2
          with:
            name: lift_dst_results
        - name: Get Src
          uses: actions/download-artifact@v2
          with:
            name: lift_src_results
        - name: Combine
          run: |
              cat lift-dst-results.json > lift-results.json
              echo '-----' >> lift-results.json
              cat lift-src-results.json >> lift-results.json
        - name: Post comments
          uses: actions/github-script@v4
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                const { promises: fs } = require('fs')
                const commit = await fs.readFile('lift-commit', 'utf8')
                console.log('Context sha: ' + context.sha)
                console.log('Real sha: ' + commit)
                const body = await fs.readFile('lift-results.json', 'utf8')
                github.pulls.createReviewComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: context.issue.number,
                    commit_id: commit,
                    body,
                    path: 'src/Data/HammingTrie.hs',
                    position: 11,
                    });
