name: MuseDev

on: pull_request

jobs:
  analyze_src:
    name: Source Branch Analysis
    runs-on: ubuntu-latest
    container:
        image: musedev/analyst
        credentials:
            username: tommd
            password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - name: Produce src artifact
          run: |
              export SRC_SHA=$(cat $GITHUB_EVENT_PATH | jq -r -j .pull_request.head.sha)
              export DST_SHA=$(cat $GITHUB_EVENT_PATH | jq -r -j .pull_request.base.sha)
              analyst -t "$GITHUB_WORKSPACE" -C $SRC_SHA > lift-src-results.json
              cat lift-src-results.json | jq . | sed 's/\\n/\n/g'
              echo "$SRC_SHA" > lift-commit
              echo -n "Source commit: " ; cat lift-commit
              echo "SRC_SHA -> DST_SHA:  $SRC_SHA -> $DST_SHA"
              git -C $GITHUB_WORKSPACE diff ${DST_SHA}..${SRC_SHA} > lift.git.diff
        - name: Upload src artifact
          uses: actions/upload-artifact@v2
          with:
            name: lift_src_results
            path: lift*

  analyze_dst:
    name: Destination Branch Analysis
    runs-on: ubuntu-latest
    container:
        image: musedev/analyst
        credentials:
            username: tommd
            password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - name: Produce dst artifact
          run: |
              export DST_SHA=$(cat $GITHUB_EVENT_PATH | jq -r -j .pull_request.base.sha)
              analyst -t "$GITHUB_WORKSPACE" -C $DST_SHA > lift-dst-results.json
              cat lift-dst-results.json | jq . | sed 's/\\n/\n/g'
        - name: Upload dst artifact
          uses: actions/upload-artifact@v2
          with:
            name: lift_dst_results
            path: lift-dst-results.json

  unify_results:
    name: Distill Result
    needs: [analyze_src, analyze_dst]
    runs-on: ubuntu-latest
    container:
        image: musedev/github-comment-composer
        credentials:
            username: tommd
            password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Get Dst
          uses: actions/download-artifact@v2
          with:
            name: lift_dst_results
        - name: Get Src
          uses: actions/download-artifact@v2
          with:
            name: lift_src_results
        - name: Combine
          run: |
              github-comment-composer lift.git.diff lift-src-results.json lift-dst-results.json > github-comments.json
        - name: Post comments
          uses: actions/github-script@v4
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                const { promises: fs } = require('fs')
                const commit = await fs.readFile('lift-commit', 'utf8')
                console.log('Commit for comment: ' + commit)
                const comments = await fs.readFile('github-comments.json', 'utf8')
                console.log('Comments string (raw): ' + comments)
                for(const comment of JSON.parse(comments)) {
                    console.log('Comment: ' + comment)
                    github.pulls.createReviewComment({
                        ...comment,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number,
                        commit_id: commit,
                        });
                }
