name: Lift

on: pull_request

jobs:
  analyze_src:
    name: Lift Static Analysis
    runs-on: ubuntu-latest
    container:
        image: musedev/analyst
        credentials:
            username: tommd
            password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Produce artifact
          run: "echo \"run: analyst -t $GITHUB_WORKSPACE -C $GITHUB_HEAD_REF\" > lift-src-results.json"
        - name: Upload artiffact
          uses: actions/upload-artifact@v2
          with:
            name: lift_src_results
            path: lift-src-results.json

  analyze_dst:
    name: Lift Static Analysis
    runs-on: ubuntu-latest
    container:
        image: musedev/analyst
        credentials:
            username: tommd
            password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Produce artifact
          run: "echo \"run: analyst -t $GITHUB_WORKSPACE -C $GITHUB_BASE_REF\" > lift-dst-results.json"
        - name: Upload artiffact
          uses: actions/upload-artifact@v2
          with:
            name: lift_dst_results
            path: lift-dst-results.json

  unify_results:
    name: Lift Static Analys Result Composition
    needs: [analyze_src, analyze_dst]
    runs-on: ubuntu-latest
    container:
        image: musedev/analyst
        credentials:
            username: tommd
            password: ${{ secrets.DOCKER_MUSE_BOT }}
    steps:
        - name: Result Interpreter
        - name: Get Dst
          uses: actions/download-artifact@v2
          with:
            name: lift_dst_results
        - name: Get Src
          uses: actions/download-artifact@v2
          with:
            name: lift_src_results
        - name: Combine
          run: |
              cat lift-dst-results.json > lift-results.json
              echo '-----' >> lift-results.json
              cat lift-src-results.json >> lift-results.json
          with:
              name: lift_results
              path: lift-results.json

  comment_on_pr:
    name: Post Lift Comments
    needs: unify_results
    runs-on: ubuntu-latest
    steps:
        - name: Get status
          uses: actions/download-artifact@v2
          with:
            name: lift_results
        - name: Post comments
          uses: actions/github-script@v4
          env:
            SHA_SRC: '${{ env.GITHUB_HEAD_REF }}'
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                const { promises: fs } = require('fs')
                const {SHA_SRC} = process.env
                const body = await fs.readFile('lift-results.json', 'utf8')
                github.pulls.createReviewComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: context.issue.number,
                    commit_id: `${SHA_SRC}`,
                    body,
                    path: 'src/Data/HammingTrie.hs',
                    position: 11,
                    });
